from datetime import datetime, timezone
from odoo import api, fields, models


class PosOrder(models.Model):
    _inherit = 'pos.order'

    epson_tse_transaction_number = fields.Integer(
        string="TSE Transaction Number",
        readonly=True,
        copy=False,
        help="Sequential transaction number assigned by the Epson USB TSE."
    )
    epson_tse_signature_counter = fields.Integer(
        string="TSE Signature Counter",
        readonly=True,
        copy=False,
        help="Monotonically increasing signature counter inside the TSE crypto chip."
    )
    epson_tse_serial_number = fields.Char(
        string="TSE Serial / CDCID",
        readonly=True,
        copy=False,
        help="Serial number or CDCID of the Epson USB TSE stick."
    )
    epson_tse_time_start = fields.Datetime(
        string="TSE Start Time",
        readonly=True,
        copy=False,
        help="Start timestamp of the transaction recorded in the TSE."
    )
    epson_tse_time_end = fields.Datetime(
        string="TSE End Time",
        readonly=True,
        copy=False,
        help="Completion timestamp of the transaction recorded in the TSE."
    )
    epson_tse_signature_value = fields.Text(
        string="TSE Signature",
        readonly=True,
        copy=False,
        help="Cryptographic digital signature generated by the BSI TR-03153 crypto chip."
    )
    epson_tse_signature_algorithm = fields.Char(
        string="TSE Signature Algorithm",
        default="ecdsa-plain-SHA256",
        readonly=True,
        copy=False
    )
    epson_tse_public_key = fields.Text(
        string="TSE Public Key",
        readonly=True,
        copy=False
    )
    epson_tse_qr_code = fields.Text(
        string="TSE QR Code Data",
        readonly=True,
        copy=False,
        help="Standardized DSFinV-K / KassenSichV formatted string encoded in the receipt QR code."
    )
    epson_tse_status = fields.Selection(
        [
            ('draft', 'Draft'),
            ('signed', 'Signed (Compliant)'),
            ('error', 'Signing Error'),
            ('emergency', 'TSE Offline Emergency (§ 7 KassenSichV)'),
        ],
        string="TSE Status",
        default='draft',
        readonly=True,
        copy=False
    )

    @api.model_create_multi
    def create(self, vals_list):
        for vals in vals_list:
            self._normalize_tse_datetimes(vals)
        return super().create(vals_list)

    def write(self, vals):
        self._normalize_tse_datetimes(vals)
        return super().write(vals)

    @api.model
    def _normalize_tse_datetimes(self, vals):
        for field in ('epson_tse_time_start', 'epson_tse_time_end'):
            val = vals.get(field)
            if val and isinstance(val, str) and ('T' in val or '+' in val):
                try:
                    dt = datetime.fromisoformat(val)
                    if dt.tzinfo:
                        dt = dt.astimezone(timezone.utc).replace(tzinfo=None)
                    vals[field] = dt.strftime('%Y-%m-%d %H:%M:%S')
                except Exception:
                    pass
